install:
  - set QTDIR=C:\Qt\5.14.2\mingw73_64
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%PATH%;%QTDIR%\bin;
  - cd "C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1"
  - ls
build_script:
  - g++ --version
  - qmake DieAgain.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
  - mingw32-make -j4